title: kiichigoFirmware Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mohas95.github.io/kiichigoFirmware

logo: "/assets/images/overview.png"
favicon_ico: "/assets/images/favicon.png"


# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
