title: kiichigoFirmware Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark



url: https://mohas95.github.io/kiichigoFirmware

# logo: "/assets/images/overview.png"
favicon_ico: "/assets/images/favicon.png"


aux_links:
  GitHub Repository: https://github.com/mohas95/kiichigoFirmware
aux_links_new_tab: true
